### ISSUE TITLE
Search the web (term)

### ISSUE THREAD

**Issue by JamieDawson** [pstringe/KIFT#16]
Assigning to Dylan.
Will probably just pull up a browser.

**Comment by dsotomay** [comment]
Hehe

On Jan 6, 2019 2:42 PM, "Jamie Dawson" <notifications@github.com> wrote:

Assigned #16 <https://github.com/pstringe/KIFT/issues/16> to @dsotomay
<https://github.com/dsotomay>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/pstringe/KIFT/issues/16#event-2056491575>, or mute the
thread
